### ISSUE TITLE
[特性需求] 请问会增加更多的字体支持吗？

### ISSUE THREAD

**Issue by tpiperatgod** [xyk953651094/SkyNewTab-Poem-React#30]
如 [江西拙楷](https://wordshub.github.io/free-font/font.html?JiangXiZhuoKai_Regular)

**Comment by xyk953651094** [comment]
已收到您的反馈，之前我也尝试过这个功能，毕竟诗词插件不支持换字体确实说不过去，但是感觉可行性不高：
* 本地字体包的体积比较大，比如您提供的江西拙楷确实很好看，但是体积高达 9.5mb，比目前整个插件的体积还大几倍，如果塞入更多的本地字体的话，整个插件的体积会高达几十mb，会很臃肿。
* 在线字体加载速度比本地慢一点，能稳定提供免费且好看的中文在线字体的网站也不好找，而且浏览器插件开发规则可能不允许引入外部网站的资源。
* 最后也存在兼容性的问题，同一个字体在部分浏览器（比如 Firefox 和 Safari）的显示效果可能不一致。

后续我会继续考虑和验证，但是不保证最终一定支持这个功能，请不要抱太大期望😂

**Comment by tpiperatgod** [comment]
了解了，感谢回复🫡
